// Regenerates preview.html from lib/data.ts + lib/metrics.ts, and checks the numbers.
//   node --experimental-strip-types scripts/render-preview.ts
import { readFileSync, writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import { pipeline, US_STAGES, IN_STAGES, type Market } from '../types/property.ts';
import { properties, complianceChecks, fmt } from '../lib/data.ts';
import { computeMetrics } from '../lib/metrics.ts';

const m = computeMetrics(properties, complianceChecks);

// --- checks: the bugs this version fixes stay fixed
const us = pipeline(properties, 'US');
assert.equal(us.find((s) => s.stage === 'Rent')!.count, 0, 'a sold building must not count as Rent');
assert.equal(us.find((s) => s.stage === 'Exit')!.count, 1, 'the sold US building is an Exit');
assert.equal(m.totalEquity, properties.reduce((s, p) => s + p.equity, 0));
assert.equal(m.exits, properties.filter((p) => p.status === 'sold').length);
assert.equal(fmt(-1_500_000), '−$1.5M');
assert.equal(fmt(950), '$950');
assert.equal(m.compliance.score, Math.round((5 / 6) * 100));
assert.deepEqual(US_STAGES.length + IN_STAGES.length, 8);

const pct = (x: number) => `${(x * 100).toFixed(0)}%`;
const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;');
const engine = (market: Market) => {
  const stages = pipeline(properties, market);
  const isUS = market === 'US';
  const active = properties.filter((r) => r.market === market && r.status !== 'sold').length;
  return `<div class="u-tile">
      <div class="u-mast"><div><div class="u-label">${isUS ? 'US · Rent Machine' : 'India · Flip Machine'}</div><div class="u-sub">${stages.map((s) => s.stage).join(' / ')}</div></div><div class="u-right"><div class="u-metric-s u-num">${fmt(m.equityByMarket[market])}</div></div></div>
      <div class="u-pipe" style="grid-template-columns:repeat(${stages.length},1fr)"><span class="u-pipe-line"></span>
        ${stages.map((s) => `<div class="u-pipe-node"${s.count ? ' data-on' : ''}><span class="u-count u-num">${String(s.count).padStart(2, '0')}</span><span class="u-stage">${s.stage}</span></div>`).join('\n        ')}
      </div>
      <div class="u-sub" style="margin-top:1.75rem">${active} active · ${isUS ? 'leveraged, held' : 'unleveraged, rotated'}</div>
    </div>`;
};
const metric = (label: string, value: string, sub: string) => `<div class="u-tile"><div class="u-label">${label}</div><div class="u-metric u-num">${value}</div><div class="u-sub">${sub}</div></div>`;
const ordered = [...complianceChecks].sort((a, b) => Number(a.ok) - Number(b.ok));

const original = readFileSync(new URL('../preview.html', import.meta.url), 'utf8');
const rawStyle = original.match(/<style>[\s\S]*?<\/style>/)![0];
const style = rawStyle.includes('.u-banner') ? rawStyle : rawStyle.replace('</style>', '.u-banner{display:inline-block;margin-bottom:2rem;padding:.35rem .7rem;border:1px solid var(--hair);border-radius:999px;font-size:var(--fs-micro);letter-spacing:.14em;text-transform:uppercase;color:var(--ink-2)}\n</style>');
const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Twin-Engine · Concept dashboard</title>
<meta name="description" content="Concept control room for a two-market real-estate platform (US BRRRR + India flips), with every figure computed from the property records. Illustrative sample data.">
${style}
</head>
<body>
<!-- GENERATED by scripts/render-preview.ts from lib/data.ts — do not edit by hand -->
<div class="u-root"><div class="u-page">
  <div class="u-banner">Concept build · illustrative sample data, not real holdings</div>
  <header class="u-mast">
    <div><div class="u-wordmark">TWIN—ENGINE</div><div class="u-sub" style="margin-top:.4rem">Family-Office Control Room</div></div>
    <div class="u-right"><div class="u-label">Platform Equity</div><div class="u-metric u-num" style="margin-top:.5rem">${fmt(m.totalEquity)}</div></div>
  </header>
  <div class="u-rule"></div>

  <section class="u-band u-band-4">
    ${metric('Gross value-add', pct(m.grossValueAdd), 'ARV ÷ basis − 1, before costs')}
    ${metric('Exits · gross multiple', m.realizedGrossMultiple === null ? '—' : `${m.realizedGrossMultiple.toFixed(2)}×`, `${m.exits} sold · ARV ÷ basis`)}
    ${metric('Active assets', String(m.active), `${pct(m.inRenovationShare)} in renovation`)}
    ${metric('Net IRR', '—', 'needs dated cash flows')}
  </section>

  <section class="u-band u-band-2">
    ${engine('US')}
    ${engine('IN')}
  </section>

  <section class="u-band" style="display:block">
    <div class="u-tile">
      <div class="u-label">Compliance · exit-critical</div>
      <div class="u-feature-grid">
        <div>
          <div class="u-hero u-num">${m.compliance.score}<span class="u-hero-unit">/ 100</span></div>
          <div class="u-meter"><span style="width:${m.compliance.score}%"></span></div>
          <div class="u-sub" style="margin-top:1.25rem;max-width:32ch">Clean Books Index — the first thing a Tier-1 acquirer diligences. Weight marks what needs attention; nothing here is decorative.</div>
        </div>
        <ul class="u-checks">
          ${ordered.map((c) => `<li class="${c.ok ? 'is-clear' : 'is-attention'}"><span class="u-check-label">${esc(c.label)}</span><span class="u-check-state">${c.ok ? 'clear' : esc(c.note ?? 'attention')}</span></li>`).join('\n          ')}
        </ul>
      </div>
    </div>
  </section>

  <footer class="u-foot"><span>Clean books · ${m.compliance.clear} of ${m.compliance.total} checks clear${m.issues.length ? ` · ${m.issues.length} data issue(s)` : ''}</span><span>USD normalized · every figure computed from the records</span></footer>
</div></div>
</body>
</html>
`;
writeFileSync(new URL('../preview.html', import.meta.url), html);
console.log('preview.html regenerated · all checks passed');
console.log({ equity: fmt(m.totalEquity), us: fmt(m.equityByMarket.US), in: fmt(m.equityByMarket.IN), valueAdd: pct(m.grossValueAdd), exitMultiple: m.realizedGrossMultiple?.toFixed(2), active: m.active, issues: m.issues });
console.log('US pipeline', us.map((s) => `${s.stage}:${s.count}`).join(' '));
